Connect back ends
Alakind/ISEP pull request #14
Opened 2024-11-06 15:21 UTC by koppenkraker13

2024-11-06 15:25 UTC, Alakind requested changes

2024-11-06 15:25 UTC, Alakind commented on applicant-server/src/main/kotlin/ut/isep/interview/api/TestController.kt
> +@RequestMapping("/test")
Interview?

2024-11-06 15:25 UTC, Alakind commented on applicant-server/src/main/kotlin/ut/isep/interview/api/TestController.kt
> +    @GetMapping("/{applicantId}/test")
Here as well

2024-11-07 10:40 UTC, eefscheef approved these changes

2024-11-07 10:48 UTC, merged