Added assignment saving feature
Alakind/ISEP pull request #32
Opened 2024-12-09 18:10 UTC by Alakind

2024-12-16 21:04 UTC, ArtemisAndApollo requested changes
Sometimes I only put a comment on one place, but add the comment to all files on the applicant side.

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +  const [assessment, setAssessment] = useState<{ sections: object[] }>({
why object[]?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +  const [sections, setSections] = useState([]);
missing typing form most useStates

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +        const data = await response.json();
why not already getting back json from the API functions?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +      try {
move this to a separate function in apiFunctions to remove some functionality from this container

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +          const responseSection = await fetch(API_SECTION_URL);
also move this to apiFunctions.tsx

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +        const initialAssignments = Array(sectionsFetched.length).fill(0);
remove commented lines

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/utils/apiFunctions.tsx
> +): Promise<unknown> {
why unknown, can't this be changed and also for the other functions?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/components/AssignmentMenu.tsx
> +    //TODO save the state of the question(s)
Can't this one be removed?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/components/AssignmentMultipleChoice.tsx
> +  const handleOptionChange = async (index: number) => {
Can you change all the functions to normal function format instead of const name = ... and don't forget the typing

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/components/AssignmentOpen.tsx
> +    event: React.ChangeEvent<HTMLTextAreaElement>
Only import ChangeEvent and not whole react to make it more efficient

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/components/AssignmentOpen.tsx
> +        onChange={(event) => handleTextChange(event)}
I miss the typing of event

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +    const fetchData = async () => {
can't you make this into separate function that are called, because this is a bit to big for one function

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/utils/apiFunctions.tsx
> +    // TODO: redirect to welcome/error page?
Seems logical you can already implement this right?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/utils/apiFunctions.tsx
> +  }
Same here

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/utils/types.tsx
> +export interface AssignmentMultipleChoiceInterface extends AssessmentInterface {
Why assessmentinterface? Shouldn't this be AssignmentInterface?

2024-12-16 21:04 UTC, SweersJ commented on frontend/applicant/src/utils/types.tsx
> +export interface AssignmentMultipleChoiceInterface extends AssessmentInterface {
And the attributes stayed the same, why not remove them with using the extension?

2024-12-17 10:13 UTC, Alakind commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +  const [assessment, setAssessment] = useState<{ sections: object[] }>({
It's not, strange. You have seen an older version for this file

2024-12-17 10:13 UTC, Alakind commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +  const [sections, setSections] = useState([]);
Same here

2024-12-17 11:23 UTC, Alakind commented on frontend/applicant/src/containers/AssessmentPageContainer.tsx
> +      try {
Done

2024-12-17 11:24 UTC, Alakind commented on frontend/applicant/src/utils/apiFunctions.tsx
> +): Promise<unknown> {
Changed to void

2024-12-17 11:35 UTC, Alakind commented on frontend/applicant/src/components/AssignmentMenu.tsx
> +    //TODO save the state of the question(s)
No, we will need to discuss, how to handle this properly

2024-12-17 11:36 UTC, Alakind commented on frontend/applicant/src/components/AssignmentMultipleChoice.tsx
> +  const handleOptionChange = async (index: number) => {
Why don't use this format?

2024-12-17 11:37 UTC, Alakind commented on frontend/applicant/src/components/AssignmentMultipleChoice.tsx
> +  const handleOptionChange = async (index: number) => {
This function does not return anything, so typing is redundant

2024-12-17 11:38 UTC, Alakind commented on frontend/applicant/src/components/AssignmentOpen.tsx
> +        onChange={(event) => handleTextChange(event)}
IMHO redundant, but if you wish so

2024-12-17 11:40 UTC, Alakind commented on frontend/applicant/src/utils/apiFunctions.tsx
> +    // TODO: redirect to welcome/error page?
No, 1) We don't have proper error page. 2) You can't use hooks outside of components

2024-12-17 11:46 UTC, ArtemisAndApollo commented on frontend/applicant/src/utils/apiFunctions.tsx
> +    // TODO: redirect to welcome/error page?
True, I forgot about that part, then a try catch could be used and put it to a toast.error(message)

2024-12-17 11:47 UTC, ArtemisAndApollo commented on frontend/applicant/src/components/AssignmentOpen.tsx
> +        onChange={(event) => handleTextChange(event)}
My IDE was complaining at some point, so I gave everything the typing they already inferred automatically.

2024-12-17 11:56 UTC, ArtemisAndApollo commented on frontend/applicant/src/components/AssignmentMultipleChoice.tsx
> +  const handleOptionChange = async (index: number) => {
I tried to be consistent with typing at the management side, by giving everything a type as well as voids

2024-12-20 14:19 UTC, ArtemisAndApollo approved these changes

2024-12-20 14:22 UTC, merged